# app/dbt_generator.py
import os
import re
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional

def _safe_name(name: str, default: str = "sidecar") -> str:
    s = re.sub(r"[^A-Za-z0-9_]+", "_", (name or "").strip())
    s = s.strip("_")
    return s or default

def _safe_col(name: str, default: str = "COL") -> str:
    s = re.sub(r"[^A-Za-z0-9_]+", "_", (name or "").strip())
    s = s.strip("_")
    return s or default

def _guess_snowflake_type(glue_or_catalog_type: str) -> str:
    dt = (glue_or_catalog_type or "").strip().lower()
    if not dt:
        return "VARCHAR"
    if any(k in dt for k in ["bigint"]):
        return "NUMBER(38,0)"
    if any(k in dt for k in ["int", "integer", "smallint", "tinyint"]):
        return "NUMBER(38,0)"
    if any(k in dt for k in ["decimal", "numeric"]):
        return "NUMBER(38,4)"
    if any(k in dt for k in ["float", "double", "real"]):
        return "FLOAT"
    if any(k in dt for k in ["bool", "boolean"]):
        return "BOOLEAN"
    if "timestamp" in dt or "datetime" in dt:
        return "TIMESTAMP_NTZ"
    if "date" in dt:
        return "DATE"
    if "time" in dt:
        return "TIME"
    if any(k in dt for k in ["variant", "json"]):
        return "VARIANT"
    return "VARCHAR"

def _parse_nullable(nullable: str) -> Optional[bool]:
    if nullable is None:
        return None
    s = str(nullable).strip().lower()
    if s in ("", "unknown", "n/a", "na"):
        return None
    if s in ("yes", "y", "true", "nullable"):
        return True
    if s in ("no", "n", "false", "not null", "not_null", "required"):
        return False
    return None

def generate_dbt_models(
    *,
    dbt_project_dir: str,
    dataset_name: str,
    source_database: str,
    source_schema: str,
    source_table: str,
    target_schema: str,
    mappings: List[Dict[str, Any]],
    quality_rules: Optional[Dict[str, Any]] = None,
    materialization: str = "view",
) -> Dict[str, str]:
    """
    Generate dbt assets from Sidecar mappings.

    What gets generated:
      - models/sidecar_generated/_sources.yml (source definition)
      - models/sidecar_generated/stg_<dataset>.sql (staging model selecting from source)
      - models/sidecar_generated/schema.yml (tests: not_null + optional regex)
      - macros/tests/regex_like.sql (generic test used by schema.yml)

    Notes:
      - This assumes your RAW data already lands in Snowflake as source_database.source_schema.source_table.
      - Sidecar's "Snowflake Bundle" can create the landing objects; dbt is for transformations on top.
    """
    proj = Path(dbt_project_dir).expanduser().resolve()
    if not (proj / "dbt_project.yml").exists():
        raise FileNotFoundError(f"dbt_project.yml not found in: {proj}")

    ds = _safe_name(dataset_name, "sidecar")
    models_dir = proj / "models" / "sidecar_generated"
    macros_dir = proj / "macros" / "tests"
    models_dir.mkdir(parents=True, exist_ok=True)
    macros_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.utcnow().isoformat() + "Z"

    src_db = source_database.strip()
    src_schema = source_schema.strip()
    src_table = source_table.strip()
    if not (src_db and src_schema and src_table):
        raise ValueError("Source Database/Schema/Table are required to generate sources.yml")

    tgt_schema = target_schema.strip() or src_schema

    # Create generic regex test macro (Snowflake-friendly: RLIKE)
    regex_macro = """{% test regex_like(model, column_name, pattern) %}
select *
from {{ model }}
where {{ column_name }} is not null
  and not ({{ column_name }} rlike '{{ pattern }}')
{% endtest %}
"""
    (macros_dir / "regex_like.sql").write_text(regex_macro, encoding="utf-8")

    # sources.yml
    source_name = f"{ds}_src"
    sources_yml = f"""version: 2

sources:
  - name: {source_name}
    database: {src_db}
    schema: {src_schema}
    tables:
      - name: {src_table}
"""
    (models_dir / "_sources.yml").write_text(sources_yml, encoding="utf-8")

    # staging model
    model_name = f"stg_{ds}"
    mat = materialization if materialization in ("view", "table", "incremental") else "view"

    select_cols = []
    for m in mappings or []:
        src = _safe_col(m.get("source_field") or "")
        tgt = _safe_col(m.get("target_field") or src)
        sf_type = _guess_snowflake_type(m.get("catalog_data_type") or m.get("target_type") or "")
        # Cast to target type in staging (safe: TRY_TO_* where possible)
        # We'll use TRY_CAST for simplicity; Snowflake supports TRY_CAST.
        expr = f"TRY_CAST(\"{src}\" AS {sf_type}) AS \"{tgt}\""
        select_cols.append(expr)

    if not select_cols:
        select_cols = ['*']

    stg_sql = f"""{{{{ config(materialized='{mat}', schema='{tgt_schema}') }}}}

-- Generated by Sidecar at {now}
select
  {',\n  '.join(select_cols)}
from {{{{ source('{source_name}', '{src_table}') }}}}
"""
    (models_dir / f"{model_name}.sql").write_text(stg_sql, encoding="utf-8")

    # schema.yml with tests
    # Build tests:
    # - if Nullable says NO -> not_null
    # - if quality_rules has regex for the column -> regex_like
    qrules = dict(quality_rules or {})
    # normalize keys so we can match either source or target field names
    norm_rules = {str(k).strip(): v for k, v in qrules.items()}

    columns_blocks = []
    for m in mappings or []:
        src = str(m.get("source_field") or "").strip()
        tgt = _safe_col(m.get("target_field") or src)
        nullable = _parse_nullable(m.get("nullable"))
        tests = []
        if nullable is False:
            tests.append("not_null")
        # regex from rules (if present)
        rx = None
        if src in norm_rules:
            rx = norm_rules.get(src)
        elif tgt in norm_rules:
            rx = norm_rules.get(tgt)
        if rx:
            # if compiled regex object, use its pattern
            pat = getattr(rx, "pattern", None) or str(rx)
            # Escape single quotes for YAML/SQL
            pat = pat.replace("'", "''")
            tests.append({"regex_like": {"pattern": pat}})
        col_yaml = {
            "name": tgt,
            "tests": tests
        }
        columns_blocks.append(col_yaml)

    # Render YAML without requiring PyYAML
    def render_col(col: Dict[str, Any]) -> str:
        lines = [f"      - name: {col['name']}"]

        tests = col.get("tests") or []
        if tests:
            lines.append("        tests:")
            for t in tests:
                if isinstance(t, str):
                    lines.append(f"          - {t}")
                elif isinstance(t, dict):
                    # only supports regex_like right now
                    for k, v in t.items():
                        lines.append(f"          - {k}:")
                        if isinstance(v, dict):
                            for kk, vv in v.items():
                                lines.append(f"              {kk}: '{vv}'")
        return "\n".join(lines)

    schema_yml = """version: 2

models:
  - name: %s
    description: "Staging model generated by Sidecar"
    columns:
%s
""" % (model_name, "\n".join(render_col(c) for c in columns_blocks) if columns_blocks else "      []")

    (models_dir / "schema.yml").write_text(schema_yml, encoding="utf-8")

    # Convenience README
    readme = f"""Sidecar dbt Generated Assets
===========================

Generated at (UTC): {now}

What was generated:
- models/sidecar_generated/_sources.yml
- models/sidecar_generated/{model_name}.sql
- models/sidecar_generated/schema.yml
- macros/tests/regex_like.sql

Next steps:
1) Ensure your profiles.yml target points at Snowflake and has access to:
   {src_db}.{src_schema}.{src_table}
2) Run:
   dbt run  --project-dir {proj}
   dbt test --project-dir {proj}

Notes:
- not_null tests are created when Catalog Nullable is 'No'
- regex_like tests are created when Sidecar Quality Rules contains a pattern for that field
"""
    (models_dir / "README_SIDE_CAR.txt").write_text(readme, encoding="utf-8")

    return {
        "generated_at": now,
        "models_dir": str(models_dir),
        "model": model_name,
        "source_name": source_name,
        "source_table": src_table,
    }
